name: Build and test MyString library
run-name: ${{ github.actor }} is building and testing on self-hosted runner
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build project
        run: |
          apt update
          apt-get install -y make g++
          make build
      - run: echo "This job's status is ${{ job.status }}."
  test:
    timeout-minutes: 2
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Test project
        run: |
          apt update
          apt-get install -y libgtest-dev cmake
          make test
      - run: echo "This job's status is ${{ job.status }}."
