name: Deploy string library on counterVM (self-hosted)
run-name: ${{ github.actor }} is deploying on GCP virtual machine
on: [push]
jobs:
  deploy:
    timeout-minutes: 2
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build project
        run: |
          apt-get update
          apt-get install -y make curl g++
          make build
      - name: Copy debian package to counter VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "mystrlib-v1.0.0.deb"
          target: /home/giacobbi
      - name: Update the package with new version
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sudo dpkg -i mystrlib-v1.0.0.deb
      - run: echo "This job's status is ${{ job.status }}."